<?xml version="1.0" ?>

<testsuites disabled="0" errors="1" failures="0" tests="1" time="6.48899507522583">
	<testsuite disabled="0" errors="1" failures="0" name="Convert" package="spacetelescope_notebooks" skipped="0" tests="1" time="6.48899507522583">
		<testcase classname="Initialization" file="/Users/jalexander/Desktop/notebooks/notebooks/DrizzlePac/Initialization/Initialization.ipynb" name="Convert_Execution" time="6.488995">
			<error message="Traceback (most recent call last):
  File &quot;/Users/jalexander/miniconda3/envs/notebooks/lib/python3.6/site-packages/nbpages/converter.py&quot;, line 126, in execute
    executor.preprocess(nb, {'metadata': {'path': self.path_only}})
  File &quot;/Users/jalexander/miniconda3/envs/notebooks/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py&quot;, line 354, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File &quot;/Users/jalexander/miniconda3/envs/notebooks/lib/python3.6/site-packages/nbconvert/preprocessors/base.py&quot;, line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File &quot;/Users/jalexander/miniconda3/envs/notebooks/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py&quot;, line 378, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
obs_table = Observations.query_criteria(obs_id='ib2j02n5qAAAAAAA', obstype='all')
download_tab = Observations.download_products(obs_table['obsid'], mrp_only=False,
                                              productSubGroupDescription=['FLC'])
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-2-8c8103d5057f&gt; in &lt;module&gt;
      1 obs_table = Observations.query_criteria(obs_id='ib2j02n5qAAAAAAA', obstype='all')
      2 download_tab = Observations.download_products(obs_table['obsid'], mrp_only=False,
----&gt; 3                                               productSubGroupDescription=['FLC'])

~/miniconda3/envs/notebooks/lib/python3.6/site-packages/astroquery/mast/core.py in download_products(self, products, download_dir, cache, curl_flag, mrp_only, **filters)
   1740                 productLists.append(self.get_product_list(oid))
   1741
-&gt; 1742             products = vstack(productLists)
   1743
   1744         # apply filters

~/miniconda3/envs/notebooks/lib/python3.6/site-packages/astropy/table/operations.py in vstack(tables, join_type, metadata_conflicts)
    285         6   8
    286     &quot;&quot;&quot;
--&gt; 287     tables = _get_list_of_tables(tables)  # validates input
    288     if len(tables) == 1:
    289         return tables[0]  # no point in stacking a single table

~/miniconda3/envs/notebooks/lib/python3.6/site-packages/astropy/table/operations.py in _get_list_of_tables(tables)
     46     # Make sure there is something to stack
     47     if len(tables) == 0:
---&gt; 48         raise ValueError('no values provided to stack.')
     49
     50     # Convert inputs (Table, Row, or anything column-like) to Tables.

ValueError: no values provided to stack.
ValueError: no values provided to stack.

" type="CellExecutionError"/>
		</testcase>
	</testsuite>
</testsuites>
